/*  Generated number - 9
	Generated number - 2
	Generated number - 8
	Generated number - 10
	Generated number - 3
	sum of all the random numbers generated by threads are:32
	Main has been executed


 */
package threads;


import java.util.*;


public class RandomNumberSumUsingThreads {

	public static void main(String[] args) {
		MyRunnable r = new MyRunnable();
		Thread thread1 = new Thread(r, "A");
		Thread thread2 = new Thread(r, "B");
		Thread thread3 = new Thread(r, "C");
		Thread thread4 = new Thread(r, "D");
		Thread thread5 = new Thread(r, "E");
		thread1.start();
		thread2.start();
		thread3.start();
		thread4.start();
		thread5.start();

		System.out.println("sum of all the random numbers generated by threads are:"+ r.getSum());
		System.out.println("Main has been executed");
	}



}

